# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Traditional Chinese Music
tagline:          'A Short Intro and Useful Map'
description:      'Resource map for global Traditaional Chinese Music Fans'
url:              https://see2.github.io
baseurl:          /

author:
  name:           'see2'
  url:            https://see2.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/see2/see2.github.io
